#!/bin/bash
ARGS=()
for var in "$@"; do
    if [ "$var" != '--make' ]
    #if true
    then
        ARGS+=("$var")
    else
        ARGS+=("--frontend")
        ARGS+=("GhcShake")
        #ARGS+=("-ffrontend-opt")
        #ARGS+=("--profile")
        #ARGS+=("-ffrontend-opt")
        #ARGS+=("--debug")
        #ARGS+=("-ffrontend-opt")
        #ARGS+=("--keep-going")
        #ARGS+=("-ffrontend-opt")
        #ARGS+=("--progress=record")
        ARGS+=("-package-db")
        ARGS+=("/home/ezyang/.cabal/store/ghc-7.11.20151220/package.db")
        ARGS+=("-package-db")
        ARGS+=("/srv/code/cabal-shake/dist-newstyle/packagedb/ghc-7.11.20151220")
        ARGS+=("-plugin-package")
        ARGS+=("ghc-shake")
    fi
done
exec "$(dirname $(realpath $0))/ghc" "${ARGS[@]}"
