#!/bin/bash
ARGS=()
for var in "$@"; do
    if [ "$var" != '--make' ]
    then
        ARGS+=("$var")
    else
        ARGS+=("--frontend")
        ARGS+=("GhcShake")
        ARGS+=("-ffrontend-opt")
        ARGS+=("--profile")
        ARGS+=("-ffrontend-opt")
        ARGS+=("--keep-going")
        ARGS+=("-ffrontend-opt")
        ARGS+=("--progress=record")
        ARGS+=("-package")
        ARGS+=("ghc-shake")
    fi
done
exec "$(dirname $(realpath $0))/ghc" "${ARGS[@]}"
